name: expense_tracker
description: Track your expense just by clicking one button with all navite
  platforms. Track your money, Track your happiness
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_theme_switcher: ^2.0.10
  animations: ^2.0.8
  bloc: ^9.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dice_bear: ^0.1.7
  dotted_border: ^2.1.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.5
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  go_router: ^14.1.4
  # google_fonts: ^6.1.0
  image_picker: ^1.0.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  liquid_swipe: ^3.1.0
  local_auth: ^2.1.8
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.2
  pie_menu: ^3.2.7
  shared_preferences: ^2.2.2
  toastification: ^2.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.3
  mocktail: ^1.0.0
  very_good_analysis: ^7.0.0

# for generating the assets path carefully
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/Bank/
    - assets/icons/MobileBanking/
    - assets/icons/other/
    - assets/illustrations/
    - fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/InterRegular.ttf
        - asset: fonts/InterItalic.ttf
          style: italic
        - asset: fonts/InterBold.ttf
          weight: 700
