name: expense_tracker
description: Track your expense just by clicking one button with all navite
  platforms. Track your money, Track your happiness
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  animated_theme_switcher: ^2.0.10
  animations: ^2.0.8
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dice_bear: ^0.1.7
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.2
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.6
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  liquid_swipe: ^3.1.0
  local_auth: ^2.1.8
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.2
  pie_menu: ^3.1.3
  shared_preferences: ^2.2.2
  toastification: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

# for generating the assets path carefully
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/Bank/
    - assets/icons/MobileBanking/
    - assets/icons/other/
    - assets/illustrations/
