const categoryData = <String, Map<String, String>>{
  'Housing': <String, String>{
    'Mortgage or rent': '🏠',
    'Property taxes': '🏡',
    'Household repairs': '🔧',
    'HOA fees': '🏘️',
    'Home improvements or renovations': '🔨',
    'Home cleaning services': '🧹',
  },
  'Transportation': <String, String>{
    'Car payment': '🚗',
    'Car warranty': '🛠️',
    'Gas': '⛽',
    'Tires': '🚘',
    'Maintenance and oil changes': '🔧',
    'Parking fees': '🅿️',
    'Repairs': '🔧',
    'Registration and DMV Fees': '🚗',
    'Public transportation expenses': '🚎',
    'Ride-sharing or taxi expenses': '🚕',
  },
  'Food': <String, String>{
    'Groceries': '🛒',
    'Restaurants': '🍽️',
    'Pet food': '🐾',
  },
  'Utilities': <String, String>{
    'Electricity': '💡',
    'Water': '🚿',
    'Garbage': '🗑️',
    'Phones': '📞',
    'Cable': '📺',
    'Internet': '🌐',
  },
  'Clothing': <String, String>{
    'Adults’ clothing': '👚',
    'Adults’ shoes': '👠',
    'Children’s clothing': '👕',
    'Children’s shoes': '👟',
  },
  'Medical/Healthcare': <String, String>{
    'Primary care': '⚕️',
    'Dental care': '🦷',
    'Specialty care (dermatologists, orthodontics, optometrists, etc.)':
        '👩‍⚕️',
    'Urgent care': '🚑',
    'Medications': '💊',
    'Medical devices': '🩺',
    'Health savings account (HSA) contributions or expenses': '💳⚕️',
    'Vision care expenses': '👓',
  },
  'Insurance': <String, String>{
    'Health insurance': '🩺🔒',
    'Homeowner’s or renter’s insurance': '🏠🔒',
    'Home warranty or protection plan': '🔒🏡',
    'Auto insurance': '🚗🔒',
    'Life insurance': '💼🔒',
    'Disability insurance': '♿🔒',
  },
  'Household Items/Supplies': <String, String>{
    'Toiletries': '🧼',
    'Laundry detergent': '🧺',
    'Dishwasher detergent': '🍽️',
    'Cleaning supplies': '🧹',
    'Tools': '🔧',
  },
  'Personal': <String, String>{
    'Gym memberships': '🏋️',
    'Haircuts': '💇',
    'Salon services': '💅',
    'Cosmetics (like makeup or services like laser hair removal)': '💄',
    'Babysitter': '👶🍼',
    'Subscriptions': '📰',
    'Hobbies or recreational activities expenses': '🎨',
    'Self-improvement or personal development expenses': '📚',
  },
  'Debt': <String, String>{
    'Personal loans': '💳',
    'Student loans': '🎓💰',
    'Credit cards': '💳',
    'Other types of loans': '💰',
  },
  'Retirement': <String, String>{
    'Financial planning': '💹',
    'Investing': '💰',
    'Continuing education expenses for personal or career development': '📚',
  },
  'Education': <String, String>{
    'Children’s college': '👨‍🎓',
    'Your college': '👩‍🎓',
    'School supplies': '📓',
    'Books': '📚',
  },
  'Savings': <String, String>{
    'Emergency fund': '💰',
    'Big purchases like a new mattress or laptop': '💻',
    'Other savings': '💰',
    'Specific savings goals (e.g., travel fund, home down payment)': '🎯',
  },
  'Gifts/Donations': <String, String>{
    'Birthday': '🎁',
    'Anniversary': '🎉',
    'Wedding': '💍🎉',
    'Christmas': '🎄',
    'Special occasion': '🎈',
    'Charities': '❤️',
  },
  'Entertainment': <String, String>{
    'Alcohol and/or bars': '🍻',
    'Games': '🎮',
    'Movies': '🎬',
    'Concerts': '🎵',
    'Vacations': '✈️',
    'Subscriptions (Netflix, Amazon, Hulu, etc.)': '📺',
  },
};
