import 'package:flutter/material.dart';

/// all expense methods
const expenseMethods = [
  ('Cash', Icons.money),
  ('Card', Icons.credit_card),
  ('Debit Card', Icons.card_membership),
  ('Credit Card', Icons.credit_card),
  ('Contactless Payment', Icons.contactless),
  ('Mobile Wallet (e.g., Apple Pay, Google Pay)', Icons.mobile_friendly),
  ('Bank Transfer', Icons.account_balance),
  ('Mobile Banking', Icons.account_balance),
  ('Online Payment', Icons.account_balance),
  ('Cryptocurrency', Icons.account_balance),
  ('Check', Icons.account_balance),
  ('Prepaid Card', Icons.account_balance),
  ('PayPal/Venmo', Icons.account_balance),
  ('Wire Transfer', Icons.account_balance),
  ('Money Order', Icons.account_balance),
  ('Gift Card', Icons.account_balance),
  ('Digital Wallet', Icons.account_balance),
  ('Automatic Payment', Icons.account_balance),
  ('Other', Icons.account_balance),
];

/// all expense types [category]
const expenseCategories = [
  ('Housing', Icons.house),
  ('    Rent/Mortgage', Icons.house),
  ('    Property Taxes', Icons.house),
  ('    Home Insurance', Icons.house),
  ('    Utilities (Electricity, Water, Gas)', Icons.house),
  ('    Repairs/Maintenance', Icons.house),
  ('Transportation', Icons.directions_car),
  ('    Gasoline/Fuel', Icons.directions_car),
  ('    Public Transit', Icons.directions_car),
  ('    Car Payments', Icons.directions_car),
  ('    Parking Fees', Icons.directions_car),
  ('    Maintenance/Repairs', Icons.directions_car),
  ('Food and Groceries', Icons.food_bank),
  ('    Groceries', Icons.food_bank),
  ('    Dining Out', Icons.food_bank),
  ('    Snacks', Icons.food_bank),
  ('Health and Fitness', Icons.health_and_safety),
  ('    Health Insurance', Icons.health_and_safety),
  ('    Doctor Visits', Icons.health_and_safety),
  ('    Gym Memberships', Icons.health_and_safety),
  ('    Medications', Icons.health_and_safety),
  ('    Wellness Products', Icons.health_and_safety),
  ('Entertainment', Icons.movie),
  ('    Movies/Theater', Icons.movie),
  ('    Concerts/Events', Icons.movie),
  ('    Subscriptions (Netflix, Spotify)', Icons.movie),
  ('    Hobbies/Recreation', Icons.movie),
  ('Personal Care', Icons.person),
  ('    Haircuts/Styling', Icons.person),
  ('    Beauty Products', Icons.person),
  ('    Spa/Massage', Icons.person),
  ('Education', Icons.school),
  ('    Tuition', Icons.school),
  ('    Books/Supplies', Icons.school),
  ('    Courses/Seminars', Icons.school),
  ('Debts and Loans', Icons.money),
  ('    Credit Card Payments', Icons.money),
  ('    Personal Loans', Icons.money),
  ('    Student Loans', Icons.money),
  ('Charity and Gifts', Icons.card_giftcard),
  ('    Donations', Icons.card_giftcard),
  ('    Gifts for Family/Friends', Icons.card_giftcard),
  ('Insurance', Icons.local_hospital),
  ('    Life Insurance', Icons.local_hospital),
  ('    Other Insurance Premiums', Icons.local_hospital),
  ('Clothing and Accessories', Icons.shopping_bag),
  ('    Clothing Purchases', Icons.shopping_bag),
  ('    Shoes/Accessories', Icons.shopping_bag),
  ('Travel', Icons.airplanemode_active),
  ('    Airfare/Transportation', Icons.airplanemode_active),
  ('    Accommodations', Icons.airplanemode_active),
  ('    Sightseeing/Activities', Icons.airplanemode_active),
  ('Savings and Investments', Icons.account_balance),
  ('    Retirement Savings', Icons.account_balance),
  ('    Stocks/Bonds', Icons.account_balance),
  ('    Emergency Fund', Icons.account_balance),
  ('Taxes', Icons.money),
  ('    Income Tax', Icons.money),
  ('    Property Tax', Icons.money),
  ('    Sales Tax', Icons.money),
  ('Miscellaneous', Icons.money),
  ('    Other/Unexpected Expenses', Icons.money),

  // Additional categories
  ('Utilities', Icons.money_off),
  ('Utilities (Electricity)', Icons.electrical_services_outlined),
  ('Utilities (Water)', Icons.water),
  ('Utilities (Gas)', Icons.gas_meter),
  ('Childcare', Icons.child_care),
  ('Child Support', Icons.child_friendly),
  ('Pet Expenses', Icons.pets),
  ('Pet Food/Vet', Icons.pets_rounded),
  ('Subscriptions (Magazines/Newspapers)', Icons.newspaper),
  ('Internet/Cable Bills', Icons.signal_wifi_connected_no_internet_4_rounded),
  ('Phone Bills', Icons.phone_android),
  ('Home Improvement', Icons.home_repair_service),
  ('Home Decor', Icons.home_work),
  ('Furniture', Icons.table_bar),
  ('Office Supplies', Icons.local_post_office),
  ('Electronics', Icons.electric_bolt),
  ('Technology/Gadgets', Icons.mobile_friendly_rounded),
  ('Freelancer/Contractor Fees', Icons.person_2_rounded),
  ('Professional Services (Legal/Accounting)', Icons.money_off),
  ('Bank Fees', Icons.money_off),
  ('ATM Fees', Icons.money_off),
  ('Late Fees/Interest Charges', Icons.money_off),
  ('Legal Fees', Icons.money_off),
  ('Tax Preparation Fees', Icons.money_off),
  ('Moving Expenses', Icons.money_off),
  ('Alimony', Icons.money_off),
  ('Child Support', Icons.money_off),
  ('Gifts for Special Occasions (Weddings, Birthdays)', Icons.money_off),
  ('Medical Expenses (Non-insured)', Icons.money_off),
  ('Medical Equipment', Icons.money_off),
  ('Emergency Expenses', Icons.money_off),
  ('Home Security', Icons.money_off),
  ('Donations (Religious/Charitable)', Icons.money_off),
  ('Gambling/Lottery', Icons.money_off),
  ('Investment Fees', Icons.money_off),
  ('Homeowners Association Fees', Icons.money_off),
  ('Membership Dues/Subscriptions (Gym, Clubs)', Icons.money_off),
  ('Vacation Home Expenses', Icons.money_off),
  ('Parking Tickets/Fines', Icons.money_off),
  ('Traffic Tickets/Fines', Icons.money_off),
  ('Legal Settlements', Icons.money_off),
  ('Reimbursements', Icons.money_off),
  ('Cash Withdrawals', Icons.money_off),
  ('Bank Transfers', Icons.money_off),
  ('Cryptocurrency Transactions', Icons.money_off),
  ('Other Income', Icons.money_off),
  ('Other Expenses', Icons.money_off),
  ('Subscription Services (e.g., Software Subscriptions)', Icons.money_off),
  ('Home Staging Costs', Icons.money_off),
  ('Property Management Fees', Icons.money_off),
  ('Landlord Insurance', Icons.money_off),
  ('Real Estate Taxes', Icons.money_off),
  ('Vacancy Costs', Icons.money_off),
  ('Professional Photography for Property', Icons.money_off),
  ('Eviction Costs', Icons.money_off),
  ('Losses from Damage or Theft', Icons.money_off),
  ('HOA Special Assessments', Icons.money_off),
  ('Home Warranty Fees', Icons.money_off),
  ('Credit Monitoring Services', Icons.money_off),
  ('Identity Theft Protection', Icons.money_off),
  ('Emergency Fund Contributions', Icons.money_off),
  ('Health Savings Account (HSA) Contributions', Icons.money_off),
  ('Investment Advisory Fees', Icons.money_off),
  ('Financial Planning Services', Icons.money_off),
  ('Tax Advisory Services', Icons.money_off),
  ('Professional Association Memberships', Icons.money_off),
  ('Business License Fees', Icons.money_off),
  ('Commercial Insurance', Icons.money_off),
  ('Supply Chain Costs', Icons.money_off),
  ('Raw Material Costs', Icons.money_off),
  ('Inventory Management Costs', Icons.money_off),
  ('Quality Control Expenses', Icons.money_off),
  ('Customer Acquisition Costs', Icons.money_off),
  ('Supplier or Vendor Payments', Icons.money_off),
  ('Sponsorship Costs', Icons.money_off),
  ('Marketing Expenses', Icons.money_off),
  ('Employee Training and Development', Icons.money_off),
  ('Travel Expenses for Business', Icons.money_off),
  ('Office Rent/Lease', Icons.money_off),
  ('Utilities for Business Premises', Icons.money_off),
  ('Equipment Leasing', Icons.money_off),
  ('Professional Networking Memberships', Icons.money_off),
  ('Technology Subscriptions (e.g., Cloud Services)', Icons.money_off),
  ('Software Development Costs', Icons.money_off),
  ('Patent/Copyright Costs', Icons.money_off),
  ('Legal Fees for Business', Icons.money_off),
  ('Business Consultancy Services', Icons.money_off),
  ('Market Research Costs', Icons.money_off),
  ('Product Launch Expenses', Icons.money_off),
  ('Public Relations Costs', Icons.money_off),
  ('Machinery or Equipment Purchases', Icons.money_off),
  ('Regulatory Compliance Costs', Icons.money_off),
  ('Customer Support Costs', Icons.money_off),
  ('R&D Expenses', Icons.money_off),
  ('Employee Benefits Costs', Icons.money_off),
  ('Insurance for Business Assets', Icons.money_off),
  ('IT Security Costs', Icons.money_off),
  ('Environmental Compliance Costs', Icons.money_off),
  ('Cybersecurity Expenses', Icons.money_off),
  ('Incident Response Costs', Icons.money_off),
  ('Disaster Recovery Costs', Icons.money_off),
  ('Training and Seminars for Employees', Icons.money_off),
  ('Office Supplies for Business', Icons.money_off),
  ('Transportation for Business Use', Icons.money_off),
  ('Miscellaneous Business Expenses', Icons.money_off),
  ('Other Expenses', Icons.money_off),
];
