import 'package:flutter/material.dart';

/// all expense methods
const expenseMethods = [
  {1: ('Cash', Icons.money)},
  {2: ('Card', Icons.credit_card)},
  {3: ('Debit Card', Icons.card_membership)},
  {4: ('Credit Card', Icons.credit_card)},
  {5: ('Contactless Payment', Icons.contactless)},
  {6: ('Mobile Wallet (e.g., Apple Pay, Google Pay)', Icons.mobile_friendly)},
  {7: ('Bank Transfer', Icons.account_balance)},
  {8: ('Mobile Banking', Icons.account_balance)},
  {9: ('Online Payment', Icons.account_balance)},
  {10: ('Cryptocurrency', Icons.account_balance)},
  {11: ('Check', Icons.account_balance)},
  {12: ('Prepaid Card', Icons.account_balance)},
  {13: ('PayPal/Venmo', Icons.account_balance)},
  {14: ('Wire Transfer', Icons.account_balance)},
  {15: ('Money Order', Icons.account_balance)},
  {16: ('Gift Card', Icons.account_balance)},
  {17: ('Digital Wallet', Icons.account_balance)},
  {18: ('Automatic Payment', Icons.account_balance)},
  {19: ('Other', Icons.account_balance)},
];

/// all expense types [category]
// const expenseCategories = [
//   {1: ('Housing', Icons.house)},
//   {2: ('    Rent/Mortgage', Icons.house)},
//   {3: ('    Property Taxes', Icons.house)},
//   {4: ('    Home Insurance', Icons.house)},
//   {5: ('    Utilities (Electricity, Water, Gas)', Icons.house)},
//   {6: ('    Repairs/Maintenance', Icons.house)},
//   {7: ('Transportation', Icons.directions_car)},
//   {8: ('    Gasoline/Fuel', Icons.directions_car)},
//   {9: ('    Public Transit', Icons.directions_car)},
//   {10: ('    Car Payments', Icons.directions_car)},
//   {11: ('    Parking Fees', Icons.directions_car)},
//   {12: ('    Maintenance/Repairs', Icons.directions_car)},
//   {13: ('Food and Groceries', Icons.food_bank)},
//   {14: ('    Groceries', Icons.food_bank)},
//   {15: ('    Dining Out', Icons.food_bank)},
//   {16: ('    Snacks', Icons.food_bank)},
//   {17: ('Health and Fitness', Icons.health_and_safety)},
//   {18: ('    Health Insurance', Icons.health_and_safety)},
//   {19: ('    Doctor Visits', Icons.health_and_safety)},
//   {20: ('    Gym Memberships', Icons.health_and_safety)},
//   {21: ('    Medications', Icons.health_and_safety)},
//   {22: ('    Wellness Products', Icons.health_and_safety)},
//   {23: ('Entertainment', Icons.movie)},
//   {24: ('    Movies/Theater', Icons.movie)},
//   {25: ('    Concerts/Events', Icons.movie)},
//   {26: ('    Subscriptions (Netflix, Spotify)', Icons.movie)},
//   {27: ('    Hobbies/Recreation', Icons.movie)},
//   {28: ('Personal Care', Icons.person)},
//   {29: ('    Haircuts/Styling', Icons.person)},
//   {30: ('    Beauty Products', Icons.person)},
//   {31: ('    Spa/Massage', Icons.person)},
//   {32: ('Education', Icons.school)},
//   {33: ('    Tuition', Icons.school)},
//   {34: ('    Books/Supplies', Icons.school)},
//   {35: ('    Courses/Seminars', Icons.school)},
//   {36: ('Debts and Loans', Icons.money)},
//   {37: ('    Credit Card Payments', Icons.money)},
//   {38: ('    Personal Loans', Icons.money)},
//   {39: ('    Student Loans', Icons.money)},
//   {40: ('Charity and Gifts', Icons.card_giftcard)},
//   {41: ('    Donations', Icons.card_giftcard)},
//   {42: ('    Gifts for Family/Friends', Icons.card_giftcard)},
//   {43: ('Insurance', Icons.local_hospital)},
//   {44: ('    Life Insurance', Icons.local_hospital)},
//   {45: ('    Other Insurance Premiums', Icons.local_hospital)},
//   {46: ('Clothing and Accessories', Icons.shopping_bag)},
//   {47: ('    Clothing Purchases', Icons.shopping_bag)},
//   {48: ('    Shoes/Accessories', Icons.shopping_bag)},
//   {49: ('Travel', Icons.airplanemode_active)},
//   {50: ('    Airfare/Transportation', Icons.airplanemode_active)},
//   {51: ('    Accommodations', Icons.airplanemode_active)},
//   {52: ('    Sightseeing/Activities', Icons.airplanemode_active)},
//   {53: ('Savings and Investments', Icons.account_balance)},
//   {54: ('    Retirement Savings', Icons.account_balance)},
//   {55: ('    Stocks/Bonds', Icons.account_balance)},
//   {56: ('    Emergency Fund', Icons.account_balance)},
//   {57: ('Taxes', Icons.money)},
//   {58: ('    Income Tax', Icons.money)},
//   {59: ('    Property Tax', Icons.money)},
//   {60: ('    Sales Tax', Icons.money)},
//   {61: ('Miscellaneous', Icons.money)},
//   {62: ('    Other/Unexpected Expenses', Icons.money)},
//   {63: ('Utilities', Icons.money_off)},
//   {64: ('Utilities (Electricity)', Icons.electrical_services_outlined)},
//   {65: ('Utilities (Water)', Icons.water)},
//   {66: ('Utilities (Gas)', Icons.gas_meter)},
//   {67: ('Childcare', Icons.child_care)},
//   {68: ('Child Support', Icons.child_friendly)},
//   {69: ('Pet Expenses', Icons.pets)},
//   {70: ('Pet Food/Vet', Icons.pets_rounded)},
//   {71: ('Subscriptions (Magazines/Newspapers)', Icons.newspaper)},
//   {
//     72: (
//       'Internet/Cable Bills',
//       Icons.signal_wifi_connected_no_internet_4_rounded
//     ),
//   },
//   {73: ('Phone Bills', Icons.phone_android)},
//   {74: ('Home Improvement', Icons.home_repair_service)},
//   {75: ('Home Decor', Icons.home_work)},
//   {76: ('Furniture', Icons.table_bar)},
//   {77: ('Office Supplies', Icons.local_post_office)},
//   {78: ('Electronics', Icons.electric_bolt)},
//   {79: ('Technology/Gadgets', Icons.mobile_friendly_rounded)},
//   {80: ('Freelancer/Contractor Fees', Icons.person_2_rounded)},
//   {81: ('Professional Services (Legal/Accounting)', Icons.money_off)},
//   {82: ('Bank Fees', Icons.money_off)},
//   {83: ('ATM Fees', Icons.money_off)},
//   {84: ('Late Fees/Interest Charges', Icons.money_off)},
//   {85: ('Legal Fees', Icons.money_off)},
//   {86: ('Tax Preparation Fees', Icons.money_off)},
//   {87: ('Moving Expenses', Icons.money_off)},
//   {88: ('Alimony', Icons.money_off)},
//   {89: ('Child Support', Icons.money_off)},
//   {90: ('Gifts for Special Occasions (Weddings, Birthdays)', Icons.money_off)},
//   {91: ('Medical Expenses (Non-insured)', Icons.money_off)},
//   {92: ('Medical Equipment', Icons.money_off)},
//   {93: ('Emergency Expenses', Icons.money_off)},
//   {94: ('Home Security', Icons.money_off)},
//   {95: ('Donations (Religious/Charitable)', Icons.money_off)},
//   {96: ('Gambling/Lottery', Icons.money_off)},
//   {97: ('Investment Fees', Icons.money_off)},
//   {98: ('Homeowners Association Fees', Icons.money_off)},
//   {99: ('Membership Dues/Subscriptions (Gym, Clubs)', Icons.money_off)},
//   {100: ('Vacation Home Expenses', Icons.money_off)},
//   {101: ('Parking Tickets/Fines', Icons.money_off)},
//   {102: ('Traffic Tickets/Fines', Icons.money_off)},
//   {103: ('Legal Settlements', Icons.money_off)},
//   {104: ('Reimbursements', Icons.money_off)},
//   {105: ('Cash Withdrawals', Icons.money_off)},
//   {106: ('Bank Transfers', Icons.money_off)},
//   {107: ('Cryptocurrency Transactions', Icons.money_off)},
//   {108: ('Other Income', Icons.money_off)},
//   {109: ('Other Expenses', Icons.money_off)},
//   {
//     110: (
//       'Subscription Services (e.g., Software Subscriptions)',
//       Icons.money_off
//     ),
//   },
//   {111: ('Home Staging Costs', Icons.money_off)},
//   {112: ('Property Management Fees', Icons.money_off)},
//   {113: ('Landlord Insurance', Icons.money_off)},
//   {114: ('Real Estate Taxes', Icons.money_off)},
//   {115: ('Vacancy Costs', Icons.money_off)},
//   {116: ('Professional Photography for Property', Icons.money_off)},
//   {117: ('Eviction Costs', Icons.money_off)},
//   {118: ('Losses from Damage or Theft', Icons.money_off)},
//   {119: ('HOA Special Assessments', Icons.money_off)},
//   {120: ('Home Warranty Fees', Icons.money_off)},
//   {121: ('Credit Monitoring Services', Icons.money_off)},
//   {122: ('Identity Theft Protection', Icons.money_off)},
//   {123: ('Emergency Fund Contributions', Icons.money_off)},
//   {124: ('Health Savings Account (HSA) Contributions', Icons.money_off)},
//   {125: ('Investment Advisory Fees', Icons.money_off)},
//   {126: ('Financial Planning Services', Icons.money_off)},
//   {127: ('Tax Advisory Services', Icons.money_off)},
//   {128: ('Professional Association Memberships', Icons.money_off)},
//   {129: ('Business License Fees', Icons.money_off)},
//   {130: ('Commercial Insurance', Icons.money_off)},
//   {131: ('Supply Chain Costs', Icons.money_off)},
//   {132: ('Raw Material Costs', Icons.money_off)},
//   {133: ('Inventory Management Costs', Icons.money_off)},
//   {134: ('Quality Control Expenses', Icons.money_off)},
//   {135: ('Customer Acquisition Costs', Icons.money_off)},
//   {136: ('Supplier or Vendor Payments', Icons.money_off)},
//   {137: ('Sponsorship Costs', Icons.money_off)},
//   {138: ('Marketing Expenses', Icons.money_off)},
//   {139: ('Employee Training and Development', Icons.money_off)},
//   {140: ('Travel Expenses for Business', Icons.money_off)},
//   {141: ('Office Rent/Lease', Icons.money_off)},
//   {142: ('Utilities for Business Premises', Icons.money_off)},
//   {143: ('Equipment Leasing', Icons.money_off)},
//   {144: ('Professional Networking Memberships', Icons.money_off)},
//   {145: ('Technology Subscriptions (e.g., Cloud Services)', Icons.money_off)},
//   {146: ('Software Development Costs', Icons.money_off)},
//   {147: ('Patent/Copyright Costs', Icons.money_off)},
//   {148: ('Legal Fees for Business', Icons.money_off)},
//   {149: ('Business Consultancy Services', Icons.money_off)},
//   {150: ('Market Research Costs', Icons.money_off)},
//   {151: ('Product Launch Expenses', Icons.money_off)},
//   {152: ('Public Relations Costs', Icons.money_off)},
//   {153: ('Machinery or Equipment Purchases', Icons.money_off)},
//   {154: ('Regulatory Compliance Costs', Icons.money_off)},
//   {155: ('Customer Support Costs', Icons.money_off)},
//   {156: ('R&D Expenses', Icons.money_off)},
//   {157: ('Employee Benefits Costs', Icons.money_off)},
//   {158: ('Insurance for Business Assets', Icons.money_off)},
//   {159: ('IT Security Costs', Icons.money_off)},
//   {160: ('Environmental Compliance Costs', Icons.money_off)},
//   {161: ('Cybersecurity Expenses', Icons.money_off)},
//   {162: ('Incident Response Costs', Icons.money_off)},
//   {163: ('Disaster Recovery Costs', Icons.money_off)},
//   {164: ('Training and Seminars for Employees', Icons.money_off)},
//   {165: ('Office Supplies for Business', Icons.money_off)},
//   {166: ('Transportation for Business Use', Icons.money_off)},
//   {167: ('Miscellaneous Business Expenses', Icons.money_off)},
//   {168: ('Other Expenses', Icons.money_off)},
// ];
