/// all expense methods
const expenseMethods = [
  'Cash',
  'Card',
  'Debit Card',
  'Credit Card',
  'Contactless Payment',
  'Mobile Wallet (e.g., Apple Pay, Google Pay)',
  'Bank Transfer',
  'Mobile Banking',
  'Online Payment',
  'Cryptocurrency',
  'Check',
  'Prepaid Card',
  'PayPal/Venmo',
  'Wire Transfer',
  'Money Order',
  'Gift Card',
  'Digital Wallet',
  'Automatic Payment',
  'Other',
];

/// all expense types [category]
const expenseCategories = [
  'Housing',
  '    Rent/Mortgage',
  '    Property Taxes',
  '    Home Insurance',
  '    Utilities (Electricity, Water, Gas)',
  '    Repairs/Maintenance',
  'Transportation',
  '    Gasoline/Fuel',
  '    Public Transit',
  '    Car Payments',
  '    Parking Fees',
  '    Maintenance/Repairs',
  'Food and Groceries',
  '    Groceries',
  '    Dining Out',
  '    Snacks',
  'Health and Fitness',
  '    Health Insurance',
  '    Doctor Visits',
  '    Gym Memberships',
  '    Medications',
  '    Wellness Products',
  'Entertainment',
  '    Movies/Theater',
  '    Concerts/Events',
  '    Subscriptions (Netflix, Spotify)',
  '    Hobbies/Recreation',
  'Personal Care',
  '    Haircuts/Styling',
  '    Beauty Products',
  '    Spa/Massage',
  'Education',
  '    Tuition',
  '    Books/Supplies',
  '    Courses/Seminars',
  'Debts and Loans',
  '    Credit Card Payments',
  '    Personal Loans',
  '    Student Loans',
  'Charity and Gifts',
  '    Donations',
  '    Gifts for Family/Friends',
  'Insurance',
  '    Life Insurance',
  '    Other Insurance Premiums',
  'Clothing and Accessories',
  '    Clothing Purchases',
  '    Shoes/Accessories',
  'Travel',
  '    Airfare/Transportation',
  '    Accommodations',
  '    Sightseeing/Activities',
  'Savings and Investments',
  '    Retirement Savings',
  '    Stocks/Bonds',
  '    Emergency Fund',
  'Taxes',
  '    Income Tax',
  '    Property Tax',
  '    Sales Tax',
  'Miscellaneous',
  '    Other/Unexpected Expenses',

  // Additional categories
  'Utilities',
  'Utilities (Electricity)',
  'Utilities (Water)',
  'Utilities (Gas)',
  'Childcare',
  'Child Support',
  'Pet Expenses',
  'Pet Food/Vet',
  'Subscriptions (Magazines/Newspapers)',
  'Internet/Cable Bills',
  'Phone Bills',
  'Home Improvement',
  'Home Decor',
  'Furniture',
  'Office Supplies',
  'Electronics',
  'Technology/Gadgets',
  'Freelancer/Contractor Fees',
  'Professional Services (Legal/Accounting)',
  'Bank Fees',
  'ATM Fees',
  'Late Fees/Interest Charges',
  'Legal Fees',
  'Tax Preparation Fees',
  'Moving Expenses',
  'Alimony',
  'Child Support',
  'Gifts for Special Occasions (Weddings, Birthdays)',
  'Medical Expenses (Non-insured)',
  'Medical Equipment',
  'Emergency Expenses',
  'Home Security',
  'Donations (Religious/Charitable)',
  'Gambling/Lottery',
  'Investment Fees',
  'Homeowners Association Fees',
  'Membership Dues/Subscriptions (Gym, Clubs)',
  'Vacation Home Expenses',
  'Parking Tickets/Fines',
  'Traffic Tickets/Fines',
  'Legal Settlements',
  'Reimbursements',
  'Cash Withdrawals',
  'Bank Transfers',
  'Cryptocurrency Transactions',
  'Other Income',
  'Other Expenses',

  // More additional categories
  'Subscription Services (e.g., Software Subscriptions)',
  'Home Staging Costs',
  'Property Management Fees',
  'Landlord Insurance',
  'Real Estate Taxes',
  'Vacancy Costs',
  'Professional Photography for Property',
  'Eviction Costs',
  'Losses from Damage or Theft',
  'HOA Special Assessments',
  'Home Warranty Fees',
  'Credit Monitoring Services',
  'Identity Theft Protection',
  'Emergency Fund Contributions',
  'Health Savings Account (HSA) Contributions',
  'Investment Advisory Fees',
  'Financial Planning Services',
  'Tax Advisory Services',
  'Professional Association Memberships',
  'Business License Fees',
  'Commercial Insurance',
  'Supply Chain Costs',
  'Raw Material Costs',
  'Inventory Management Costs',
  'Quality Control Expenses',
  'Customer Acquisition Costs',
  'Supplier or Vendor Payments',
  'Sponsorship Costs',
  'Marketing Expenses',
  'Employee Training and Development',
  'Travel Expenses for Business',
  'Office Rent/Lease',
  'Utilities for Business Premises',
  'Equipment Leasing',
  'Professional Networking Memberships',
  'Technology Subscriptions (e.g., Cloud Services)',
  'Software Development Costs',
  'Patent/Copyright Costs',
  'Legal Fees for Business',
  'Business Consultancy Services',
  'Market Research Costs',
  'Product Launch Expenses',
  'Public Relations Costs',
  'Machinery or Equipment Purchases',
  'Regulatory Compliance Costs',
  'Customer Support Costs',
  'R&D Expenses',
  'Employee Benefits Costs',
  'Insurance for Business Assets',
  'IT Security Costs',
  'Environmental Compliance Costs',
  'Cybersecurity Expenses',
  'Incident Response Costs',
  'Disaster Recovery Costs',
  'Training and Seminars for Employees',
  'Office Supplies for Business',
  'Transportation for Business Use',
  'Miscellaneous Business Expenses',
  'Other Expenses'
];
